# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: "Jay Stevens"
title: Schemepunk
email: jaystevens42@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is Jay Stevens' personal portfolio and blog. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jay2645.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
repository: "jay2645/jay2645.github.io"
twitter:
    username: "schemepunk"
facebook:
    username: "jay2645"
social:
  type:  "Person"
  name:  "Jay Stevens"
  links:
    - "https://github.com/jay2645"
    - "https://www.linkedin.com/in/jay2645/"
    - "https://twitter.com/schemepunk"
    - "https://facebook.com/jay2645"
    
author:
  name: "Jay Stevens"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Passionate game developer seeks like-minded game to develop."
  location: >-
  1101 Stevens Ave, Apt 59
  Santa Ana, CA, 92707
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/schemepunk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jay2645"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/jay2645"
    - label: "GitHub"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jay2645/"

search: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/schemepunk"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jay2645"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/jay2645"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jay2645/"
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      related: true

# Build settings
locale: "en-US"
timezone: America/Los_Angeles
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
plugins:
  - jekyll-feed
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
